params:
  seed: ${...seed}

  algo:
    name: a2c_continuous

  model:
    name: continuous_a2c_logstd

  network:
    name: actor_critic
    separate: False
    space:
      continuous:
        mu_activation: None
        sigma_activation: None

        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: True
    mlp:
      units: [256, 256, 64]
      activation: elu
      d2rl: False
      
      initializer:
        name: default
      regularizer:
        name: None

  load_checkpoint: False # flag which sets whether to load the checkpoint
  load_path: ${...checkpoint} # path to the checkpoint to load

  config:
    name: PickCube-v1
    full_experiment_name: ${.name}
    env_name: maniskill
    multi_gpu: ${....multi_gpu}
    ppo: True
    mixed_precision: True
    normalize_input: True
    normalize_value: True
    value_bootstrap: True
    num_actors: 512
    reward_shaper:
      scale_value: 0.01
    normalize_advantage: True
    gamma: 0.9
    tau: 0.9
    learning_rate: 3e-4
    lr_schedule: adaptive
    schedule_type: legacy
    kl_threshold: 0.1
    max_epochs: 40
    save_best_after: 200
    save_frequency: 50
    grad_norm: 1.0
    entropy_coef: 0.0
    truncate_grads: False
    e_clip: 0.2
    horizon_length: 50
    minibatch_size: 800
    mini_epochs: 16
    critic_coef: 2
    clip_value: True
    seq_len: 4
    bounds_loss_coef: 0.0001